branches:
  only:
  - master
language: ruby
rvm:
- 2.3.3
services:
- postgresql
before_install:
- gem install bundler
bundler_args: "--without development --jobs=3"
cache: bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- echo deploying...
- bundle exec rails assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: ROaFbKs4Yhixz4AZw6TPuMCOtwQQH+Srp/aD3WH6uXLQpaRTWEp2GARqPE3GohcQnpp3AlY5zqmWVDKcqNUsWA37h99VhmedOcG23jDZNIYUbw9Ck0S5W7EOHoUzWn0u8q/RfJ/An+9MKlA8oxG8q3DzLBYGDcce4ExdaiOOtVsAH81M628bVfjxf6rlrQjlkyXehkzDC8PkaCCc+bxExSN6s7kELxokVC0zpCh9yVibRTq0gzpjkRYAqnde33hqy3Re9hyjhNt3YzL5zPgME0hPY5IHgC23GZGbs5ljcJlRL+4MxeOnSVLYS2i19jaRtyHs1ikkOsOHLebacDq0BxyjTqHMNvef4yqGvr7ZPPXzyBKlgz82nHb+yUxU4a3mN3807hSAlUC/r5QyPqyTfw4fk2+llXA4cuqDAO6RXK6J0sg2a2VNpitqvFR3Go3Uh6mzJjv+K2ByRdOhmxApLW1LLIwGqj1kU9C9BtaFB7LEmyvnxnO4gfv24sKamqa/xbacOC5oJ7c8Uk4yQc9xKqzX8PoSx6uj8et0d7XTm7+NRpGl7ieFSDtehI0MT0lDIACKbVnzhYemJnhvE0GZtqta/bWKL0BZ7Sbi5yeTCbAszBFNczoHw3RpEGW3z8fMhBZB03t0vlrk6EXJgor1GNJ6N/KhvyagTCi3ODivlEo=
  app: task-driver
  on:
    repo: enpitut2018/task_driver
notifications:
  slack:
    secure: Re4pUkKvjvo7ignEHFi7lnIXI5SqdwnHqLCvJHA8Rc5fOZHJqKhh4ow9CmWoFqOdBLZ6TLzoh61zYgBGqLnI07PkVLY1lrs67v/Jjx2I6p6d0RMn2X2v2ofC2vCiTGfPmY/8jgl1Z8BuK86+LE18MVTr/3nhMBr+cXu5D5yemQfbP/kgXBD1RBeKMUYM2Avxwh2YVdZIQqFGvzl74YWbRvuwbtFssYlhvWUAgYAFvtxL5oQmq+Lztk36TvvG/OiZYD4DHu1542qp/0jaWApr0RyB57LxI9o6nxHnk+R7r+CIMmv4INW211PTPAnA9HitgP3dUQkpLJLzNhRn3mopTPBHkWb1HGMKh1+Tf2cLt6PnYOwc4dpF86X8HjOMCMNwns9fuy2vgxEPBUIIDTCWOGEdEzCxAY0ACptaP6oqUAiwKjbrIqs2eHnQNQeKCRqsp7u4quAws/u61Z7RZCWO3zmbvnv5xoWQrQcBPk51whNYazAkvxKhKxmE8eAGFii+gFwG2cfltc2QVeCh9V4hJk/b6q1+vZ2Uw6niJOtkV5F7f1H6G+VOrMId9sZ3/mlzLUl4LyN2moQmLdnSEsSztwKhclkTslUESuOdFVVQs0IqhtjdxOJu0PRFEIlI04d7tQt5PBMZEIxTYYUglP2KNoLetDXAMpXRtpD9MzPpt30=
