branches:
  only:
  - master
language: ruby
rvm:
- 2.3.3
services:
- postgresql
before_install:
- gem install bundler
bundler_args: "--without development --jobs=3"
cache: bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- bundle exec rails assets:precompile

deploy:
  provider: heroku
  api_key:
    secure: Xz9duXfxNQzf6MhXfWaKp0c559Juu2KaDHfHqpxPLDcvQSHm/blrc6zdb1ZojF7X1Hc+uX/ThcdF5EWg+sTTYSAFfx/xQjAmeVDEofay0PLsBlVCzkUWc/HegoNv0VM/C9RATj9vTdBN1dpw4X4aIxpRY4M1vKkgsHcoOkZFZFDkoBR2Iiar6CNAk6JcXWEG/DveZ/LrVxaW3p77vd2CwZhQmIjg4jc5QNB3/NUldYCQ5Nr6Fo+ShDqNZeH8D0daSbpNsKqv3p788Gg3Vf0URU0YK7N6uPFsPnBjEJkwHlEnfqqbI24+hs01pWgNhoHNT1zLbnnuMFhSdU8URAdJZDP5f+GYfV9W77L7GOyrAMv39KoFlFdl/Oh42MEUHCHACQKm98QBSNhUFhGr6I8tQRdHfymQRXeEx3trNG6kESb+M9ysA3lay6DgbTXpmxPsoP5p0+OvKKyjadle66TptNSzWj0ExNyHyfu7Xp+id0VrS6e/VyNOTE9jplZCTpVd3EdGm5ZtmqmU6Anb9zClWVOFBW2iq5b94tsFS8s6NsgvuGhcKFkZjE/fL2dPzbgOPQKVDuzYhwvFlUFerbxBf43307BnLJ63sQkYlq2UK2tl1rZX0sOoZDAqVmPgXT/vaRYg4veBzgel7PtCynViVzuuzjauPHKZjsJ6+m6jnCI=
  run: "rake db:migrate"
  app: task-driver
  on:
    repo: enpitut2018/task_driver

notifications:
  slack:
    secure: Re4pUkKvjvo7ignEHFi7lnIXI5SqdwnHqLCvJHA8Rc5fOZHJqKhh4ow9CmWoFqOdBLZ6TLzoh61zYgBGqLnI07PkVLY1lrs67v/Jjx2I6p6d0RMn2X2v2ofC2vCiTGfPmY/8jgl1Z8BuK86+LE18MVTr/3nhMBr+cXu5D5yemQfbP/kgXBD1RBeKMUYM2Avxwh2YVdZIQqFGvzl74YWbRvuwbtFssYlhvWUAgYAFvtxL5oQmq+Lztk36TvvG/OiZYD4DHu1542qp/0jaWApr0RyB57LxI9o6nxHnk+R7r+CIMmv4INW211PTPAnA9HitgP3dUQkpLJLzNhRn3mopTPBHkWb1HGMKh1+Tf2cLt6PnYOwc4dpF86X8HjOMCMNwns9fuy2vgxEPBUIIDTCWOGEdEzCxAY0ACptaP6oqUAiwKjbrIqs2eHnQNQeKCRqsp7u4quAws/u61Z7RZCWO3zmbvnv5xoWQrQcBPk51whNYazAkvxKhKxmE8eAGFii+gFwG2cfltc2QVeCh9V4hJk/b6q1+vZ2Uw6niJOtkV5F7f1H6G+VOrMId9sZ3/mlzLUl4LyN2moQmLdnSEsSztwKhclkTslUESuOdFVVQs0IqhtjdxOJu0PRFEIlI04d7tQt5PBMZEIxTYYUglP2KNoLetDXAMpXRtpD9MzPpt30=
