branches:
  only:
  - master
language: ruby
rvm:
- 2.3.3
services:
- postgresql
before_install:
- gem install bundler
- chmod +x bin/travis.sh
bundler_args: "--without development --jobs=3"
cache: bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.travis.yml config/database.yml
- bundle exec rails db:create
- bundle exec rails db:migrate
script:
- bin/travis.sh
deploy:
  provider: heroku
  api_key:
    secure: lDV+kLEOO2O367zXK/xERR5uD4POSaL4GwhY9CTTVsgGBZEBZ1sBbMXUWreOixST0Rx+M6lxpWxPtSiRJ3ScZd8TP+wnifPAXgLPaScMBRlpwiL9hOsKexCrxj4/I1jiJ3rHCUhWBsITpnrnm2V5JLcMcMCJIVUreHSPRuYf7saVvi6WBKL/dd9YDUPUHL633CHQuP0+YfQ8woLi1/G6V5iREtQOxOJjvua8BzxMoHncZniMI4ifA7X8VMI35tA9Loir4FqDcNewV5URSpauxZ/LQ74FUTVhv1/nvHs//3MMnyay19i+bp0eL67KVAe7960mIFRdGxENhZCGXwZxAc+Y5cxxKBYjAMS6s3DCKMRA8SkSxd5lKcomwqxDKUS1j0mZTJTUmd9ISubYiyBKEnCvh0TO1Kb4tKzjndINmjtam4KPEB1xIbl3Yh3YmWoe3Lyh1Z8CQEJFzXlbYNcNA5QzrDlpVjywawhvl0oxGnqhCPb2b36BMD5eZ1r+qVINr/fz98zbGa+yAv0g0l5NrunoUSW70iJ+cfK8v2Go61mbXPFfdsHUHGCss9cBoP3oKBtrq2+mxiUEUNVgE9dG7TFK3+IHi5GW9Rw9EIkr28LePHHiYwUVETnupHL47s3qtQd+nPAB4hHJdl+b8xjtqrom6tgGvLsQrhhjjArkCOE=
  app: task-driver
  on:
    repo: enpitut2018/task_driver
notifications:
  slack:
    secure: Re4pUkKvjvo7ignEHFi7lnIXI5SqdwnHqLCvJHA8Rc5fOZHJqKhh4ow9CmWoFqOdBLZ6TLzoh61zYgBGqLnI07PkVLY1lrs67v/Jjx2I6p6d0RMn2X2v2ofC2vCiTGfPmY/8jgl1Z8BuK86+LE18MVTr/3nhMBr+cXu5D5yemQfbP/kgXBD1RBeKMUYM2Avxwh2YVdZIQqFGvzl74YWbRvuwbtFssYlhvWUAgYAFvtxL5oQmq+Lztk36TvvG/OiZYD4DHu1542qp/0jaWApr0RyB57LxI9o6nxHnk+R7r+CIMmv4INW211PTPAnA9HitgP3dUQkpLJLzNhRn3mopTPBHkWb1HGMKh1+Tf2cLt6PnYOwc4dpF86X8HjOMCMNwns9fuy2vgxEPBUIIDTCWOGEdEzCxAY0ACptaP6oqUAiwKjbrIqs2eHnQNQeKCRqsp7u4quAws/u61Z7RZCWO3zmbvnv5xoWQrQcBPk51whNYazAkvxKhKxmE8eAGFii+gFwG2cfltc2QVeCh9V4hJk/b6q1+vZ2Uw6niJOtkV5F7f1H6G+VOrMId9sZ3/mlzLUl4LyN2moQmLdnSEsSztwKhclkTslUESuOdFVVQs0IqhtjdxOJu0PRFEIlI04d7tQt5PBMZEIxTYYUglP2KNoLetDXAMpXRtpD9MzPpt30=
